import streamlit as st
import pandas as pd
import joblib
import os


# page configuration
st.set_page_config(
    page_title="Insurance Claim Predictor",
    page_icon="+",
    layout="centered"
)

# Loading model artifacts
REQUIRED_FILES = [
    "scaler.pkl",
    "label_encoder_gender.pkl",
    "label_encoder_diabetic.pkl",
    "label_encoder_smoker.pkl",
    "best_model.pkl",
]  # .pkl files generated by train_model.py

missing = [f for f in REQUIRED_FILES if not os.path.exists(f)]
if missing:
    st.error(
        f"Missing model artifact(s): {missing}\n\n"
        "Please run `python train_model.py` first to generate the required files."
    )
    st.stop()

@st.cache_resource
def load_artifacts():
    _scaler      = joblib.load("scaler.pkl")
    _le_gender   = joblib.load("label_encoder_gender.pkl")
    _le_diabetic = joblib.load("label_encoder_diabetic.pkl")
    _le_smoker   = joblib.load("label_encoder_smoker.pkl")
    _model       = joblib.load("best_model.pkl")
    return _scaler, _le_gender, _le_diabetic, _le_smoker, _model


scaler, le_gender, le_diabetic, le_smoker, model = load_artifacts()

# user interface

st.title("Health Insurance Claim Predictor")
st.write("Enter the details below to estimate your insurance claim amount.")

st.divider()

with st.form("input_form"):
    col1, col2 = st.columns(2)

    with col1:
        age           = st.number_input("Age",                min_value=0,    max_value=100,  value=30)
        bmi           = st.number_input("BMI",                min_value=10.0, max_value=60.0, value=25.0, step=0.1)
        children      = st.number_input("Number of Children", min_value=0,    max_value=8,    value=0)

    with col2:
        bloodpressure = st.number_input("Blood Pressure",     min_value=60,   max_value=200,  value=120)
        gender        = st.selectbox("Gender",   options=le_gender.classes_)
        diabetic      = st.selectbox("Diabetic", options=le_diabetic.classes_)
        smoker        = st.selectbox("Smoker",   options=le_smoker.classes_)

    submitted = st.form_submit_button("Predict Claim Amount", use_container_width=True)

# prediction logic

if submitted:
    input_data = pd.DataFrame({
        "age":           [age],
        "gender":        [gender],
        "bmi":           [bmi],
        "bloodpressure": [bloodpressure],
        "diabetic":      [diabetic],
        "children":      [children],
        "smoker":        [smoker],
    })

    # Encoding the categorical columns
    input_data["gender"]   = le_gender.transform(input_data["gender"])
    input_data["diabetic"] = le_diabetic.transform(input_data["diabetic"])
    input_data["smoker"]   = le_smoker.transform(input_data["smoker"])

    # Scaling the numerical columns
    num_cols = ["age", "bmi", "bloodpressure", "children"]
    input_data[num_cols] = scaler.transform(input_data[num_cols])

    prediction = model.predict(input_data)[0]

    st.divider()
    st.success(f"**Estimated Insurance Claim Amount: ${prediction:,.2f}**")

    # Contextual risk note based on prediction value
    if prediction < 5000:
        st.info("Low risk profile — estimated claim is below average.")
    elif prediction < 15000:
        st.warning("Moderate risk profile — estimated claim is around average.")
    else:
        st.error("High risk profile — estimated claim is above average.")

# footer

st.divider()
st.caption("Built with Streamlit · Model trained using scikit-learn & XGBoost")